## Data Cleaning

- checks for corrupted images 
- resizes and pads to square images 
- saves into a structured cleaned folder 
- use parallel processing with ThreadPoolExecutor

### Imports

In [ ]:
from pathlib import Path
from PIL import Image
import cv2
import albumentations as A
from tqdm.auto import tqdm
import pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
import os 
import sys 
from IPython.display import display # display the image in the notebook

root_path = os.path.abspath(Path(os.getcwd()).parent)
sys.path.append(root_path)

from preprocessing.data_loader import load_deepFashion, load_fashion_ges
from preprocessing.data_cleaning import is_corrupted,resize_and_save, process_image,clean_folder, pad_resize

### Check if an image is corrupted

In [ ]:
# sample image path
path_img = r"D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Data\DeepFashion\Images\img\Zippered_Sweatpants\img_00000001.jpg"
path_img_corrupted = r"D. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Data\DeepFashion\Images\img\Zippered_Sweatpants\img_00000001.jpg"

list_paths = [path_img, path_img_corrupted]

for i, path in enumerate(list_paths):
    if is_corrupted(path):
        print(f"image {i}: the image is corrupted")
    else:
        print(f"image {i}: the image isn't corrupted")

### display the image

In [ ]:
with Image.open(path_img) as img:
    display(img)

### resize and pad to (256,256)

In [ ]:
img = cv2.imread(path_img)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

augmented = pad_resize(image=img)
aug_img = augmented['image']

In [ ]:
# before the transformation 
import matplotlib.pyplot as plt

plt.subplot(1,2,1)
plt.imshow(img)
plt.title(f"Original: size {img.shape}")
plt.axis('off')


plt.subplot(1,2,2)
plt.imshow(aug_img)
plt.title(f"Augmented Image: size {aug_img.shape}")
plt.axis('off')

plt.show()

### after augmentation we want to save it into a destination folder

In [ ]:
# dst_file = Path("Test_save/preprocessed/img_00000001.jpg")

# resize_and_save(path_img, dst_file)

### check if the image is not corrupted resize and save the image into a specific folder and it's ignore it

In [ ]:
def process_image(row, root_path: Path, data_name: str):
    """
    parameters:
        - row: an iterable form the df annotation that we create from data_loader script
        - root_path: path to source image 
    goals:
        - Check if the image is corrupted:
            - ignore it and return the path
        - else:
            - resize and save that image  into a clean path
            - return the dst path
            
        - remove corrupted rows from the dataframe 
        - replace the old file path with the new cleaned path 
    """
    src = Path(root_path) / row.file
    clean_root = C.CLEAN_DIR / data_name
    
    # if corrupted return its path
    if is_corrupted(src):
        print(f"Corrupted image skipped: {src}")
        return None

    # build the destination folder to copy the image in the dest folder
    dst = clean_root / row.split / row.category.replace(" ", "_") / Path(row.file).name
    resize_and_save(src, dst)
    if data_name == "DeepFashion":
        return {
            "file": str(dst.relative_to(clean_root)),
            "category": row.category,
            "x_1": row.x_1,
            "y_1": row.y_1,
            "x_2": row.x_2,
            "y_2": row.y_2,
            "split": row.split
        }
    elif data_name == "Fashion-gen":
        return {
        "file": str(dst.relative_to(clean_root)),
        "gender": row.gender,
        "masterCategory": row.masterCategory,
        "category": row.category,
        "articleType": row.articleType,
        "baseColour": row.baseColour,
        "season": row.season,
        "year" : row.year,
        "usage": row.usage,
        "productDisplayName": row.productDisplayName,
        "split": row.split
        }

In [19]:
deep_data_path = r"D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Dataset_Clean\DeepFashion\annotation\DeepFashion.csv"
gen_data_path = r"D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Dataset_Clean\FashionGen\annotation\FashionGen.csv"

deepFashion = pd.read_csv(deep_data_path)
deepFashion.head()

,file,category_label,category,category_type,region,x_1,y_1,x_2,y_2,split
0,img/Sheer_Pleated-Front_Blouse/img_00000001.jpg,3,Bomber,1,upper,72,79,232,273,train
1,img/Sheer_Pleated-Front_Blouse/img_00000002.jpg,3,Bomber,1,upper,67,59,155,161,train
2,img/Sheer_Pleated-Front_Blouse/img_00000003.jpg,3,Bomber,1,upper,65,65,156,200,val
3,img/Sheer_Pleated-Front_Blouse/img_00000004.jpg,3,Bomber,1,upper,51,62,167,182,train
4,img/Sheer_Pleated-Front_Blouse/img_00000005.jpg,3,Bomber,1,upper,46,88,166,262,test

In [11]:
len(deepFashion)

289222

In [12]:
Fashion_gen = pd.read_csv(gen_data_path)
Fashion_gen.head()

,file,gender,masterCategory,category,articleType,baseColour,season,year,usage,productDisplayName,split
0,15970.jpg,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011,Casual,Turtle Check Men Navy Blue Shirt,train
1,39386.jpg,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012,Casual,Peter England Men Party Blue Jeans,train
2,59263.jpg,Women,Accessories,Watches,Watches,Silver,Winter,2016,Casual,Titan Women Silver Watch,train
3,21379.jpg,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011,Casual,Manchester United Men Solid Black Track Pants,train
4,53759.jpg,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012,Casual,Puma Men Grey T-shirt,train

In [15]:
root_path_deep_fashion = r"D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Data\DeepFashion\Images"
root_path_fashion_gen = r"D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Data\Fashion-gen\images"

In [17]:

for i,row in enumerate(deepFashion.itertuples(index=False)):
    if i < 5:
        print(f"row {i + 1}: {row}\n")

row 1: Pandas(file='img/Sheer_Pleated-Front_Blouse/img_00000001.jpg', category_label=3, category='Bomber', category_type=1, region='upper', x_1=72, y_1=79, x_2=232, y_2=273, split='train')

row 2: Pandas(file='img/Sheer_Pleated-Front_Blouse/img_00000002.jpg', category_label=3, category='Bomber', category_type=1, region='upper', x_1=67, y_1=59, x_2=155, y_2=161, split='train')

row 3: Pandas(file='img/Sheer_Pleated-Front_Blouse/img_00000003.jpg', category_label=3, category='Bomber', category_type=1, region='upper', x_1=65, y_1=65, x_2=156, y_2=200, split='val')

row 4: Pandas(file='img/Sheer_Pleated-Front_Blouse/img_00000004.jpg', category_label=3, category='Bomber', category_type=1, region='upper', x_1=51, y_1=62, x_2=167, y_2=182, split='train')

row 5: Pandas(file='img/Sheer_Pleated-Front_Blouse/img_00000005.jpg', category_label=3, category='Bomber', category_type=1, region='upper', x_1=46, y_1=88, x_2=166, y_2=262, split='test')

In [18]:
for i,row in enumerate(tqdm(deepFashion.itertuples(index=False), total=len(deepFashion), desc="preprocessing the images")):
    if i < 5:
        output = process_image(row, root_path_deep_fashion, "DeepFashion")
        

print(output)

preprocessing the images:  81%|████████  | 234314/289222 [00:00<00:00, 1190756.82it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

preprocessing the images: 100%|██████████| 289222/289222 [00:00<00:00, 1186429.48it/s]

{'file': 'test\\Bomber\\img_00000005.jpg', 'category': 'Bomber', 'x_1': 46, 'y_1': 88, 'x_2': 166, 'y_2': 262, 'split': 'test'}

### now we will group all of this together

In [ ]:
# Fashion_gen_cleaned = clean_folder(Fashion_gen, root_path_fashion_gen, "Fashion-gen")
# Fashion_gen_cleaned.head()

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   0%|          | 0/44424 [00:00<?, ?it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   0%|          | 121/44424 [00:00<00:36, 1204.99it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   1%|          | 242/44424 [00:00<00:38, 1135.75it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   1%|          | 356/44424 [00:00<00:40, 1090.04it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   1%|          | 466/44424 [00:00<00:41, 1064.11it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   1%|▏         | 573/44424 [00:00<00:44, 978.48it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   2%|▏         | 676/44424 [00:00<00:44, 989.79it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   2%|▏         | 785/44424 [00:00<00:42, 1020.25it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   2%|▏         | 992/44424 [00:00<00:43, 1006.54it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   3%|▎         | 1199/44424 [00:01<00:42, 1015.53it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   3%|▎         | 1301/44424 [00:01<00:43, 996.70it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   3%|▎         | 1401/44424 [00:01<00:43, 996.14it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   3%|▎         | 1501/44424 [00:01<00:44, 964.44it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   4%|▎         | 1599/44424 [00:01<00:44, 964.69it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   4%|▍         | 1696/44424 [00:01<00:44, 964.24it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   4%|▍         | 1795/44424 [00:01<00:43, 969.47it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   4%|▍         | 1998/44424 [00:06<06:42, 105.31it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   5%|▍         | 2217/44424 [00:06<03:28, 202.55it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   5%|▌         | 2443/44424 [00:06<01:57, 356.23it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   6%|▌         | 2661/44424 [00:06<01:17, 539.09it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   6%|▋         | 2885/44424 [00:06<00:56, 734.34it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   7%|▋         | 3107/44424 [00:07<00:47, 876.07it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   7%|▋         | 3317/44424 [00:07<00:51, 803.71it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   8%|▊         | 3409/44424 [00:07<00:51, 791.08it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   8%|▊         | 3580/44424 [00:07<00:52, 781.14it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   9%|▊         | 3777/44424 [00:07<00:46, 874.83it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   9%|▉         | 3975/44424 [00:08<00:43, 929.36it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:   9%|▉         | 4171/44424 [00:08<00:46, 870.64it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  10%|▉         | 4439/44424 [00:08<00:45, 873.90it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  10%|█         | 4527/44424 [00:08<00:49, 807.63it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  11%|█         | 4707/44424 [00:08<00:47, 842.84it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  11%|█         | 4877/44424 [00:09<00:47, 834.19it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  11%|█         | 4961/44424 [00:09<00:49, 801.68it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  11%|█▏        | 5042/44424 [00:09<01:04, 612.75it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  12%|█▏        | 5172/44424 [00:09<01:14, 527.23it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  12%|█▏        | 5401/44424 [00:10<00:59, 653.65it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  12%|█▏        | 5548/44424 [00:10<00:56, 691.65it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  13%|█▎        | 5705/44424 [00:10<00:52, 740.15it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  13%|█▎        | 5869/44424 [00:10<00:49, 779.31it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  14%|█▎        | 6038/44424 [00:10<00:47, 805.41it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  14%|█▍        | 6126/44424 [00:11<00:46, 820.64it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  14%|█▍        | 6291/44424 [00:11<00:47, 809.11it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  15%|█▍        | 6455/44424 [00:11<00:47, 792.88it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  15%|█▍        | 6611/44424 [00:11<00:51, 740.86it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  15%|█▌        | 6760/44424 [00:11<00:52, 716.11it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
Corrupted image skipped: D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Data\Fashion-gen\images\39403.jpg
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  16%|█▌        | 6916/44424 [00:12<00:50, 739.55it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  16%|█▌        | 7078/44424 [00:12<00:48, 768.70it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  16%|█▋        | 7319/44424 [00:12<00:47, 786.60it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  17%|█▋        | 7480/44424 [00:12<00:46, 786.08it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  17%|█▋        | 7636/44424 [00:13<00:48, 759.87it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  17%|█▋        | 7713/44424 [00:13<00:48, 750.05it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  18%|█▊        | 7866/44424 [00:13<00:49, 746.06it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  18%|█▊        | 8109/44424 [00:13<00:47, 770.76it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  19%|█▊        | 8269/44424 [00:13<00:46, 780.04it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  19%|█▉        | 8433/44424 [00:14<00:45, 796.00it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  19%|█▉        | 8592/44424 [00:14<00:46, 777.70it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  20%|█▉        | 8681/44424 [00:14<00:44, 810.54it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  20%|█▉        | 8842/44424 [00:14<00:47, 747.96it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  20%|██        | 8918/44424 [00:14<00:48, 738.60it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  20%|██        | 8993/44424 [00:14<01:10, 504.90it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  20%|██        | 9106/44424 [00:15<01:22, 426.65it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  21%|██        | 9269/44424 [00:15<01:01, 573.11it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  21%|██        | 9424/44424 [00:15<00:53, 651.82it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  21%|██▏       | 9511/44424 [00:15<00:49, 707.89it/s]

the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  22%|██▏       | 9672/44424 [00:15<00:46, 753.91it/s]

the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  22%|██▏       | 9928/44424 [00:16<00:42, 809.64it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  23%|██▎       | 10094/44424 [00:16<00:42, 813.01it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  23%|██▎       | 10258/44424 [00:16<00:42, 801.67it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  23%|██▎       | 10431/44424 [00:16<00:41, 827.08it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  24%|██▎       | 10514/44424 [00:17<00:41, 821.21it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  24%|██▍       | 10678/44424 [00:17<00:42, 801.74it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

cleaning/resizing/saving_to_clean_folder:  24%|██▍       | 10825/44424 [00:17<00:54, 621.06it/s]

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctlythe image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctlythe image is saved correctly
the image is saved correctly

the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly
the image is saved correctly

In [ ]:
len(Fashion_gen_cleaned)

In [ ]:
deepFashion_cleaned = clean_folder(deepFashion, root_path_deep_fashion, "DeepFashion")
deepFashion_cleaned.head()

In [ ]:
print(len(deepFashion_cleaned))
print(len(Fashion_gen_cleaned))

In [ ]:
from pathlib import Path
IN_ROOT = Path(r"D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Dataset_Clean\DeepFashion")
imgs = list(IN_ROOT.rglob("*.jpg")) + list(IN_ROOT.rglob("*.jpeg")) + list(IN_ROOT.rglob("*.png"))
print(len(imgs))

In [ ]:
IN_ROOT = Path("D:\03. Projects\technocolabs_projects\1. Deep-Learning-Driven-Virtual-Fashion-Fitting\Dataset_Clean\Fashion-gen")
imgs = list(IN_ROOT.rglob("*.jpg")) + list(IN_ROOT.rglob("*.jpeg")) + list(IN_ROOT.rglob("*.png"))
print(len(imgs))